;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-paren
        c-indent-line-or-region
        indent-for-tab-command
        kill-region
        ))

(setq mc/cmds-to-run-once
      '(
        ))
